import{S as w,i as m,a as p}from"./assets/vendor-c493984e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const f=document.querySelector(".gallery");let h=new w(".gallery a",{docClose:!0,close:!0});function y(r){if(r.length===0)m.show({message:"Sorry, there are no images matching your search query. Please try again!"}),f.innerHTML="";else{const e=r.map(({largeImageURL:a,webformatURL:s,tags:t,likes:o,views:c,comments:S,downloads:q})=>`<li class="list">
  <a href="${a}">
    <img src='${s}' alt='${t}'/>
    <div class="item-wrap">
    <h2 class="item-text">Like<p>${o}</p></h2>
    <h2 class="item-text">Views<p>${c}</p></h2>
    <h2 class="item-text">Comments<p>${S}</p></h2>
    <h2 class="item-text">Downloads<p>${q}</p></h2>
  </div>
  </li>`).join("");f.insertAdjacentHTML("beforeend",e),h&&h.refresh()}}const x="https://pixabay.com",P="api/",$="44791676-0ec883c6e453828f8c76360bc";p.defaults.baseURL=x;function g({q:r="",page:e=1,pageSize:a=15}={}){return p.get(P,{params:{key:$,q:r,page:e,per_page:a,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(({data:s})=>s).catch(s=>{console.log(s)})}const u=document.querySelector("form"),E=document.querySelector(".gallery"),l=document.querySelector(".loader"),i=document.querySelector(".button-load");document.querySelector(".spinner");d(i);u.addEventListener("submit",O);const n={q:"",page:1,pageSize:15,maxPage:0};async function O(r){if(r.preventDefault(),E.innerHTML="",n.page=1,n.q=u.elements.search.value.trim(),!n.q){m.error({title:"Рядок не може бути пустим"});return}M(i),L(i,l);try{const{hits:e,total:a}=await g(n);n.maxPage=Math.ceil(a/n.pageSize),y(e),e.length>0&&e.length!==a?(v(i,l),i.addEventListener("click",b)):d(i)}catch{}finally{u.reset()}}async function b(r){n.page+=1,L(i,l);try{const{hits:e}=await g(n);y(e);const s=document.querySelector(".list").getBoundingClientRect().height;window.scrollBy({top:s*4,behavior:"smooth"})}catch(e){console.log(e)}finally{v(i,l),n.page===n.maxPage&&(console.log("We're sorry, but you've reached the end of search results."),d(i),i.removeEventListener("click",b))}}function d(r){r.classList.add("is-hidden")}function M(r){r.classList.remove("is-hidden")}function L(r,e){r.disabled=!0,e.style.display="block"}function v(r,e){r.disabled=!1,e.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
