import{S as w,i as m,a as y}from"./assets/vendor-c493984e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const f=document.querySelector(".gallery");let p=new w(".gallery a",{docClose:!0,close:!0});function g(o){if(o.length===0)m.show({message:"Sorry, there are no images matching your search query. Please try again!"}),f.innerHTML="";else{const t=o.map(({largeImageURL:i,webformatURL:s,tags:e,likes:r,views:u,comments:b,downloads:v})=>`<li class="list">
  <a href="${i}">
    <img src='${s}' alt='${e}'height="152" width="360"/>
    <div class="item-wrap">
    <h2 class="item-text">Like<p>${r}</p></h2>
    <h2 class="item-text">Views<p>${u}</p></h2>
    <h2 class="item-text">Comments<p>${b}</p></h2>
    <h2 class="item-text">Downloads<p>${v}</p></h2>
  </div>
  </li>`).join("");f.insertAdjacentHTML("beforeend",t),p&&p.refresh()}}const q="https://pixabay.com",x="api/",P="44791676-0ec883c6e453828f8c76360bc";y.defaults.baseURL=q;function L({q:o="",page:t=1,pageSize:i=15}={}){return y.get(x,{params:{key:P,q:o,page:t,per_page:i,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(({data:s})=>s).catch(s=>{console.log(s)})}const h=document.querySelector("form"),$=document.querySelector(".gallery"),l=document.querySelector(".loader"),a=document.querySelector(".button-load");document.querySelector(".spinner");c(l);c(a);h.addEventListener("submit",E);a.addEventListener("click",S);const n={q:"",page:1,pageSize:15,maxPage:0};async function E(o){if(o.preventDefault(),$.innerHTML="",n.page=1,n.q=h.elements.search.value.trim(),!n.q){m.error({title:"Рядок не може бути пустим"});return}d(l),c(a);try{const{hits:t,total:i}=await L(n);n.maxPage=Math.ceil(i/n.pageSize),g(t),t.length>0&&t.length!==i?(d(a),c(l)):(c(a),c(l))}catch{}finally{h.reset()}}async function S(o){n.page+=1,c(a),d(l);try{const{hits:t}=await L(n);g(t);const s=document.querySelector(".list").getBoundingClientRect().height;window.scrollBy({top:s*4,behavior:"smooth"})}catch(t){console.log(t)}finally{c(l),d(a),n.page===n.maxPage&&(m.show({message:"We're sorry, but you've reached the end of search results."}),c(a),a.removeEventListener("click",S))}}function c(o){o.style.display="none"}function d(o){o.style.display="flex"}
//# sourceMappingURL=commonHelpers.js.map
