import{S as x,i as h,a as p}from"./assets/vendor-c493984e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const f=document.querySelector(".gallery");let m=new x(".gallery a",{docClose:!0,close:!0});function y(r){if(r.length===0)h.show({message:"Sorry, there are no images matching your search query. Please try again!"}),f.innerHTML="";else{const e=r.map(({largeImageURL:i,webformatURL:a,tags:t,likes:o,views:c,comments:S,downloads:q})=>`<li class="list">
  <a href="${i}">
    <img src='${a}' alt='${t}'/>
    <div class="item-wrap">
    <h2 class="item-text">Like<p>${o}</p></h2>
    <h2 class="item-text">Views<p>${c}</p></h2>
    <h2 class="item-text">Comments<p>${S}</p></h2>
    <h2 class="item-text">Downloads<p>${q}</p></h2>
  </div>
  </li>`).join("");f.innerHTML=e,m&&m.refresh()}}const P="https://pixabay.com",w="api/",$="44791676-0ec883c6e453828f8c76360bc";p.defaults.baseURL=P;function g({q:r="",page:e=1,pageSize:i=15}={}){return p.get(w,{params:{key:$,q:r,page:e,per_page:i,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(({data:a})=>a).catch(a=>{console.log(a)})}const u=document.querySelector("form"),E=document.querySelector(".gallery"),l=document.querySelector(".loader"),n=document.querySelector(".button-load");document.querySelector(".spinner");d(n);u.addEventListener("submit",O);const s={q:"",page:1,pageSize:15,maxPage:0};async function O(r){if(r.preventDefault(),E.innerHTML="",s.page=1,s.q=u.elements.search.value.trim(),!s.q){h.error({title:"Рядок не може бути пустим"});return}M(n),b(n,l);try{const{hits:e,total:i}=await g(s);s.maxPage=Math.ceil(i/s.pageSize),y(e),e.length>0&&e.length!==i?(v(n,l),n.addEventListener("click",L)):d(n)}catch{}finally{u.reset()}}async function L(r){s.page+=1,b(n,l);try{const{hits:e}=await g(s);y(e)}catch(e){console.log(e)}finally{v(n,l),s.page===s.maxPage&&(console.log("We're sorry, but you've reached the end of search results."),d(n),n.removeEventListener("click",L))}}function d(r){r.classList.add("is-hidden")}function M(r){r.classList.remove("is-hidden")}function b(r,e){r.disabled=!0,e.style.display="block"}function v(r,e){r.disabled=!1,e.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
